2. root:
- '*'

5. documentation:
- 'docs/**/*'
- 'README.md'

4. source:
- 'src/**/*'

3. github:
- '.github/**/*'

6. dependencies:
- 'package-lock.json'
- 'package.json'

7. public:
- 'public/**/*'

8. assets:
- 'assets/**/*'

9. electron:
- 'electron/**/*'

10. prettier:
- '.prettierignore'
- '.prettierrc'

11. config:
- 'tsconfig.json'
- 'tsconfig.node.json'
- 'vite.config.ts'
- 'electron-builder.json5'
- '.gitignore'
- '.eslintrc.cjs'
